import * as ImagePicker from 'expo-image-picker'
import { Image, ImageBackground } from 'expo-image'
import { StatusBar } from 'expo-status-bar'
import { VideoView, useVideoPlayer } from 'expo-video'
import { useEffect, useMemo, useState } from 'react'
import { Alert, KeyboardAvoidingView, Modal, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import type { Session } from '@supabase/supabase-js'
import DateTimePicker from '@react-native-community/datetimepicker'
import { Bath, HeartPulse, ShieldCheck } from 'lucide-react-native'

import { formatMomentDate, formatRecordDate } from '../../../../packages/shared/src/date'
import type { HealthCategory, HealthEntry, Moment, MomentType, PageId } from '../../../../packages/shared/src/types'
import { createHealthEntry, createTimelineEntry, maxVideoBytes, uploadTimelineMedia } from '../lib/api'
import { isSupabaseConfigured, supabase } from '../lib/supabase'
import { useMobileData } from '../context/use-mobile-data'

const c = { bg: '#f4f6f1', paper: '#fff', ink: '#1d2821', muted: '#657269', soft: '#e7ede5', line: 'rgba(35,55,42,.14)', green: '#3e6d47', pale: '#e4eee0', warm: '#b47b3c', danger: '#b45f58' }
const hero = require('../../assets/nut/hero.jpg')
const portrait = require('../../assets/nut/portrait.png')
const fallbackImages = [require('../../assets/nut/by-the-sea.jpg'), require('../../assets/nut/shower.jpg'), require('../../assets/nut/come.jpg')]
const months = ['全年', '1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
const categories = [{ id: 'bath', title: '洗澡记录', Icon: Bath }, { id: 'deworm', title: '驱虫记录', Icon: ShieldCheck }, { id: 'cycle', title: '生理周期', Icon: HeartPulse }] satisfies { id: HealthCategory; title: string; Icon: typeof Bath }[]
type MediaDraft = { uri: string; mimeType: string; fileName: string; fileSize?: number }

const today = () => new Date().toISOString().slice(0, 10)
const validDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value)
function Video({ source, contain = false }: { source: string; contain?: boolean }) {
  const player = useVideoPlayer(source, (item) => { item.loop = false })
  return <VideoView player={player} style={styles.media} nativeControls contentFit={contain ? 'contain' : 'cover'} />
}

export function NutMobileApp({ page }: { page: PageId }) {
  const { session, timeline, health, timelineError, healthError, refreshing, canManage, refresh, onRefresh, removeTimeline, removeHealth } = useMobileData()
  const [selected, setSelected] = useState<Moment | null>(null)
  const [loginOpen, setLoginOpen] = useState(false)
  const [timelineOpen, setTimelineOpen] = useState(false)
  const [healthOpen, setHealthOpen] = useState(false)

  let content: React.ReactNode
  if (page === 'home') content = <Home />
  else if (page === 'timeline') content = <Timeline moments={timeline} error={timelineError} canManage={canManage} refreshing={refreshing} onRefresh={onRefresh} onOpen={setSelected} onDelete={removeTimeline} onAdd={() => session && canManage ? setTimelineOpen(true) : setLoginOpen(true)} />
  else if (page === 'health') content = <Health entries={health} error={healthError} signedIn={Boolean(session)} refreshing={refreshing} onRefresh={onRefresh} onDelete={removeHealth} onAdd={() => session ? setHealthOpen(true) : setLoginOpen(true)} />
  else content = <About />

  const homeActive = page === 'home'
  return <SafeAreaView style={[styles.app, !homeActive && styles.appLight]} edges={['top']}><StatusBar style={homeActive ? 'light' : 'dark'} animated />{content}<Viewer moment={selected} onClose={() => setSelected(null)} /><Login visible={loginOpen} onClose={() => setLoginOpen(false)} />{session ? <TimelineForm visible={timelineOpen} session={session} onClose={() => setTimelineOpen(false)} onSaved={async () => { setTimelineOpen(false); await refresh(session) }} /> : null}{session ? <HealthForm visible={healthOpen} session={session} onClose={() => setHealthOpen(false)} onSaved={async () => { setHealthOpen(false); await refresh(session) }} /> : null}</SafeAreaView>
}

export default function HomeScreen() {
  return <NutMobileApp page="home" />
}

function Home() {
  return <ImageBackground source={hero} style={styles.home} imageStyle={styles.heroImage} contentFit="cover" contentPosition="center"><View style={styles.heroShade} /><View style={styles.heroCopy}><Text style={styles.eyebrowLight}>BLACK SHIBA DIARY</Text><Text style={styles.heroTitle}>坚果</Text><Text style={styles.heroSubtitle}>欢迎来到我的日记本</Text><Text style={styles.heroMeta}>成长档案  ·  记录每一个值得记住的时刻</Text></View></ImageBackground>
}

function Timeline({ moments, error, canManage, refreshing, onRefresh, onOpen, onDelete, onAdd }: { moments: Moment[]; error: string; canManage: boolean; refreshing: boolean; onRefresh: () => Promise<void>; onOpen: (item: Moment) => void; onDelete: (id: string) => void; onAdd: () => void }) {
  const [year, setYear] = useState('')
  const [month, setMonth] = useState('全年')
  const [query, setQuery] = useState('')
  const years = useMemo(() => [...new Set(moments.map((item) => item.date.slice(0, 4)))].sort((a, b) => b.localeCompare(a)), [moments])
  useEffect(() => { if (!year && years.length) setYear(years[0]) }, [year, years])
  const visible = useMemo(() => moments.filter((item) => (!year || item.date.startsWith(year)) && (month === '全年' || Number(item.date.slice(5, 7)) === Number(month.replace('月', ''))) && (item.title + ' ' + (item.body ?? '') + ' ' + item.tags.join(' ')).toLowerCase().includes(query.trim().toLowerCase())), [moments, month, query, year])
  return <ScrollView style={styles.scroll} contentContainerStyle={styles.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void onRefresh()} tintColor={c.green} />}><Header eyebrow="MEMORIES" title="时间线" action={canManage ? '新增记录' : '管理员登录'} onAction={onAdd} /><TextInput value={query} onChangeText={setQuery} style={styles.search} placeholder="搜索点滴" placeholderTextColor={c.muted} />{error ? <Notice text={error} /> : null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{years.map((item) => <Chip key={item} label={item} active={year === item} onPress={() => setYear(item)} />)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{months.map((item) => <Chip key={item} label={item} active={month === item} onPress={() => setMonth(item)} />)}</ScrollView><Text style={styles.count}>{year || '全部'} 年 · {month} · {visible.length} 条记录</Text><View style={styles.timeline}>{visible.map((item, index) => <View key={item.id} style={styles.timelineRow}><Text style={styles.date}>{formatMomentDate(item.date)}</Text><View style={styles.moment}><MomentMedia item={item} index={index} onOpen={() => onOpen(item)} /><Text style={styles.momentTitle}>{item.title}</Text>{item.body ? <Text style={styles.body}>{item.body}</Text> : null}<View style={styles.tags}>{item.tags.map((tag) => <Text key={tag} style={styles.tag}>{tag}</Text>)}</View>{canManage ? <Delete onConfirm={() => onDelete(item.id)} /> : null}</View></View>)}</View>{!visible.length ? <Text style={styles.empty}>这一段时间，还没有留下记录。</Text> : null}</ScrollView>
}

function MomentMedia({ item, index, onOpen }: { item: Moment; index: number; onOpen: () => void }) {
  if (item.type === 'text') return <Pressable onPress={onOpen} style={styles.textMedia}><Text style={styles.quote}>“</Text></Pressable>
  if (item.type === 'video') return <Pressable onPress={onOpen} style={styles.videoCover}><Text style={styles.videoLabel}>播放视频</Text></Pressable>
  return <Pressable onPress={onOpen}><Image source={item.media ? { uri: item.media } : fallbackImages[index % fallbackImages.length]} style={styles.media} contentFit="cover" transition={150} /></Pressable>
}

function Health({ entries, error, signedIn, refreshing, onRefresh, onDelete, onAdd }: { entries: HealthEntry[]; error: string; signedIn: boolean; refreshing: boolean; onRefresh: () => Promise<void>; onDelete: (id: string) => void; onAdd: () => void }) {
  return <ScrollView style={styles.scroll} contentContainerStyle={styles.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void onRefresh()} tintColor={c.green} />}><Header eyebrow="CARE LOG" title="健康档案" action={signedIn ? '新增记录' : '管理员登录'} onAction={onAdd} /><Text style={styles.lead}>把每一次细心照料，都留在这里。</Text>{error ? <Notice text={error} /> : null}{categories.map((category) => { const records = entries.filter((item) => item.category === category.id).sort((a, b) => b.date.localeCompare(a.date)); return <View key={category.id} style={styles.healthCard}><View style={styles.healthHead}><View style={styles.healthIcon}><category.Icon color={c.green} size={20} strokeWidth={1.8} /></View><Text style={styles.healthTitle}>{category.title}</Text><Text style={styles.total}>{records.length} 次</Text></View>{records.length ? records.map((entry) => <View key={entry.id} style={styles.healthRow}><View style={styles.grow}><Text style={styles.recordDate}>{formatRecordDate(entry.date)}</Text>{entry.note ? <Text style={styles.body}>{entry.note}</Text> : null}</View>{signedIn ? <Delete onConfirm={() => onDelete(entry.id)} /> : null}</View>) : <Text style={styles.emptyInline}>暂无记录</Text>}</View> })}</ScrollView>
}

function About() {
  return <ScrollView style={styles.scroll} contentContainerStyle={styles.page}><Header eyebrow="ABOUT NUT" title="关于坚果" /><Image source={portrait} style={styles.portrait} contentFit="cover" /><Text style={styles.aboutName}>坚果 <Text style={styles.nick}>Nut</Text></Text><Text style={styles.aboutIntro}>一只黑色柴犬。她把普通的午后、散步的风和每一次抬头，都变成值得记住的时刻。</Text><View style={styles.profile}>{[['品种', '黑色柴犬'], ['生日', '2024 年 6 月'], ['来到家里', '2024 年 9 月']].map(([key, value]) => <View key={key} style={styles.profileRow}><Text style={styles.profileKey}>{key}</Text><Text style={styles.profileValue}>{value}</Text></View>)}</View><Text style={styles.eyebrow}>她喜欢</Text><View style={styles.tags}>{['爱晒太阳', '喜欢草地', '零食雷达', '慢热黏人'].map((item) => <Text key={item} style={styles.trait}>{item}</Text>)}</View></ScrollView>
}

function Header({ eyebrow, title, action, onAction }: { eyebrow: string; title: string; action?: string; onAction?: () => void }) {
  return <View style={styles.header}><View><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text></View>{action && onAction ? <Pressable onPress={onAction} style={styles.headerAction}><Text style={styles.headerActionText}>{action}</Text></Pressable> : null}</View>
}
function Chip({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.chipOn]}><Text style={[styles.chipText, active && styles.chipTextOn]}>{label}</Text></Pressable> }
function Notice({ text }: { text: string }) { return <View style={styles.notice}><Text style={styles.noticeText}>{text}</Text></View> }
function Delete({ onConfirm }: { onConfirm: () => void }) { return <Pressable onPress={() => Alert.alert('删除记录', '删除后无法恢复。', [{ text: '取消', style: 'cancel' }, { text: '删除', style: 'destructive', onPress: onConfirm }])}><Text style={styles.delete}>删除</Text></Pressable> }
function Viewer({ moment, onClose }: { moment: Moment | null; onClose: () => void }) {
  return <Modal visible={Boolean(moment)} transparent animationType="fade" onRequestClose={onClose}>{moment ? <View style={styles.viewer}><SafeAreaView style={styles.viewerSafe}><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>关闭</Text></Pressable><View style={styles.viewerPanel}>{moment.type === 'video' && moment.media ? <Video source={moment.media} contain /> : moment.type === 'text' ? <Text style={styles.viewerQuote}>{moment.body ?? moment.title}</Text> : <Image source={moment.media ? { uri: moment.media } : fallbackImages[0]} style={styles.viewerImage} contentFit="contain" />}<Text style={styles.viewerTitle}>{moment.title}</Text>{moment.body ? <Text style={[styles.body, styles.viewerBody]}>{moment.body}</Text> : null}</View></SafeAreaView></View> : null}</Modal>
}

function Login({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  async function submit() { if (!supabase) { setMessage('请先在 apps/mobile/.env 中配置 Supabase。'); return } setSaving(true); setMessage(''); const result = await supabase.auth.signInWithPassword({ email, password }); setSaving(false); if (result.error) setMessage(result.error.message); else { setPassword(''); onClose() } }
  return <Sheet visible={visible} title="管理员登录" onClose={onClose}><Text style={styles.sheetLead}>{isSupabaseConfigured ? '登录后可新增和删除记录。' : '请先在 apps/mobile/.env 中配置 Supabase 连接信息。'}</Text><TextInput value={email} onChangeText={setEmail} style={styles.input} placeholder="管理员邮箱" placeholderTextColor={c.muted} autoCapitalize="none" keyboardType="email-address" /><TextInput value={password} onChangeText={setPassword} style={styles.input} placeholder="密码" placeholderTextColor={c.muted} secureTextEntry />{message ? <Text style={styles.noticeText}>{message}</Text> : null}<Button label={saving ? '登录中...' : '登录'} disabled={saving || !email || !password} onPress={() => void submit()} /></Sheet>
}

function TimelineForm({ visible, session, onClose, onSaved }: { visible: boolean; session: Session; onClose: () => void; onSaved: () => Promise<void> }) {
  const [type, setType] = useState<MomentType>('photo'); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [date, setDate] = useState(today()); const [time, setTime] = useState(''); const [tags, setTags] = useState(''); const [media, setMedia] = useState<MediaDraft | null>(null); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  async function selectMedia() { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: type === 'photo' ? 'images' : 'videos', quality: type === 'photo' ? .78 : 1 }); if (result.canceled) return; const asset = result.assets[0]; const mimeType = asset.mimeType ?? (type === 'photo' ? 'image/jpeg' : 'video/mp4'); if (type === 'video' && (asset.fileSize ?? 0) > maxVideoBytes) { setMessage('视频文件超过 45MB，无法上传。'); return } setMedia({ uri: asset.uri, mimeType, fileName: asset.fileName ?? 'nut-' + Date.now() + '.' + (mimeType.split('/')[1] ?? 'jpg'), fileSize: asset.fileSize }); setMessage('') }
  async function submit() { if (!title.trim() || !validDate(date) || (type !== 'text' && !media)) { setMessage('请填写标题和有效日期，并选择需要上传的媒体。'); return } setSaving(true); setMessage(''); try { const mediaPath = media ? await uploadTimelineMedia(session, media.uri, media.mimeType, media.fileName) : undefined; await createTimelineEntry(session, { type, title: title.trim(), body: body.trim() || undefined, date, time: time.trim() || undefined, tags: tags.split(',').map((item) => item.trim()).filter(Boolean), mediaPath }); setTitle(''); setBody(''); setDate(today()); setTime(''); setTags(''); setMedia(null); await onSaved() } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败，请稍后重试。') } finally { setSaving(false) } }
  return <Sheet visible={visible} title="新增时间线记录" onClose={onClose}><View style={styles.chips}>{(['photo', 'video', 'text'] as MomentType[]).map((item) => <Chip key={item} label={item === 'photo' ? '图片' : item === 'video' ? '视频' : '文字'} active={type === item} onPress={() => { setType(item); setMedia(null); setMessage('') }} />)}</View><TextInput value={title} onChangeText={setTitle} style={styles.input} placeholder="给这一刻起个名字" placeholderTextColor={c.muted} /><DateField value={date} onChange={setDate} /><TextInput value={time} onChangeText={setTime} style={styles.input} placeholder="时间：HH:mm（可选）" placeholderTextColor={c.muted} autoCapitalize="none" /><TextInput value={body} onChangeText={setBody} style={[styles.input, styles.textarea]} placeholder="记录一些点滴（可选）" placeholderTextColor={c.muted} multiline /><TextInput value={tags} onChangeText={setTags} style={styles.input} placeholder="标签，用逗号分隔（可选）" placeholderTextColor={c.muted} />{type !== 'text' ? <Pressable style={styles.mediaPicker} onPress={() => void selectMedia()}><Text style={styles.mediaPickerTitle}>{media ? media.fileName : '选择' + (type === 'photo' ? '图片' : '视频')}</Text><Text style={styles.mediaPickerHint}>{type === 'photo' ? '图片将以压缩质量导入' : '最大 45MB'}</Text></Pressable> : null}{message ? <Text style={styles.noticeText}>{message}</Text> : null}<Button label={saving ? '保存中...' : '保存记录'} disabled={saving} onPress={() => void submit()} /></Sheet>
}

function HealthForm({ visible, session, onClose, onSaved }: { visible: boolean; session: Session; onClose: () => void; onSaved: () => Promise<void> }) {
  const [category, setCategory] = useState<HealthCategory>('bath'); const [date, setDate] = useState(today()); const [note, setNote] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  async function submit() { if (!validDate(date)) { setMessage('请输入 YYYY-MM-DD 格式的日期。'); return } setSaving(true); setMessage(''); try { await createHealthEntry(session, { category, date, note: note.trim() || undefined }); setDate(today()); setNote(''); await onSaved() } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败，请稍后重试。') } finally { setSaving(false) } }
  return <Sheet visible={visible} title="新增健康记录" onClose={onClose}><View style={styles.chips}>{categories.map((item) => <Chip key={item.id} label={item.title} active={category === item.id} onPress={() => setCategory(item.id)} />)}</View><DateField value={date} onChange={setDate} /><TextInput value={note} onChangeText={setNote} style={[styles.input, styles.textarea]} placeholder="备注（可选）" placeholderTextColor={c.muted} multiline />{message ? <Text style={styles.noticeText}>{message}</Text> : null}<Button label={saving ? '保存中...' : '保存记录'} disabled={saving} onPress={() => void submit()} /></Sheet>
}

function Sheet({ visible, title, onClose, children }: { visible: boolean; title: string; onClose: () => void; children: React.ReactNode }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView style={styles.keyboardAvoider} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><View style={styles.sheetOverlay}><SafeAreaView style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{title}</Text><Pressable onPress={onClose}><Text style={styles.closeText}>关闭</Text></Pressable></View><ScrollView contentContainerStyle={styles.sheetContent} keyboardShouldPersistTaps="handled" keyboardDismissMode={Platform.OS === 'ios' ? 'interactive' : 'on-drag'}>{children}</ScrollView></SafeAreaView></View></KeyboardAvoidingView></Modal> }
function Button({ label, disabled, onPress }: { label: string; disabled?: boolean; onPress: () => void }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, disabled && styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable> }

function DateField({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const [open, setOpen] = useState(false)
  const current = validDate(value) ? new Date(value + 'T12:00:00') : new Date()
  return <><Pressable style={styles.input} onPress={() => setOpen(true)}><Text style={{ color: c.ink, fontSize: 14 }}>{value}</Text></Pressable>{open ? <DateTimePicker value={current} mode="date" onChange={(_event, date) => { setOpen(false); if (date) onChange(date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0')) }} /> : null}</>
}

const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: '#000' }, appLight: { backgroundColor: c.bg }, home: { flex: 1, justifyContent: 'flex-end' }, heroImage: { backgroundColor: '#020604' }, heroShade: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(18,25,19,.24)' }, heroCopy: { alignItems: 'center', paddingHorizontal: 24, paddingBottom: 138 }, eyebrowLight: { color: '#fff', fontSize: 11, fontWeight: '700', letterSpacing: 2 }, heroTitle: { color: '#fff', fontSize: 70, lineHeight: 82, fontWeight: '700', letterSpacing: 8, marginTop: 10 }, heroSubtitle: { color: '#fff', fontSize: 15, marginTop: 9 }, heroMeta: { color: 'rgba(255,255,255,.9)', fontSize: 11, marginTop: 20 },
  scroll: { flex: 1, backgroundColor: c.bg }, page: { padding: 22, paddingBottom: 132, gap: 14 }, header: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 8 }, eyebrow: { color: c.green, fontSize: 11, fontWeight: '700', letterSpacing: 1.5, marginBottom: 6 }, title: { color: c.ink, fontSize: 33, lineHeight: 40, fontWeight: '700' }, headerAction: { borderBottomWidth: 1, borderColor: c.line, paddingBottom: 5 }, headerActionText: { color: c.muted, fontSize: 12 }, lead: { color: c.muted, lineHeight: 22, marginTop: -5 }, search: { backgroundColor: c.paper, borderWidth: 1, borderColor: c.line, borderRadius: 10, padding: 12, color: c.ink, fontSize: 14 },
  chips: { flexDirection: 'row', gap: 8, paddingRight: 20 }, chip: { borderWidth: 1, borderColor: c.line, borderRadius: 8, backgroundColor: c.paper, paddingVertical: 8, paddingHorizontal: 12 }, chipOn: { backgroundColor: c.pale, borderColor: 'rgba(62,109,71,.4)' }, chipText: { color: c.muted, fontSize: 13 }, chipTextOn: { color: c.green, fontWeight: '700' }, count: { color: c.warm, fontSize: 12 }, timeline: { gap: 22 }, timelineRow: { flexDirection: 'row', gap: 13 }, date: { width: 82, color: c.warm, fontSize: 12, fontWeight: '700', paddingTop: 2, lineHeight: 18 }, moment: { flex: 1, gap: 7 }, media: { width: '100%', aspectRatio: 1.15, borderRadius: 12, backgroundColor: c.soft }, textMedia: { width: '100%', aspectRatio: 1.15, borderRadius: 12, backgroundColor: c.pale, justifyContent: 'center', alignItems: 'center' }, quote: { color: c.green, fontSize: 60, lineHeight: 60 }, videoCover: { width: '100%', aspectRatio: 1.15, borderRadius: 12, backgroundColor: c.ink, justifyContent: 'center', alignItems: 'center' }, videoLabel: { color: '#fff', fontSize: 14 }, momentTitle: { color: c.ink, fontSize: 17, fontWeight: '700' }, body: { color: c.muted, fontSize: 13, lineHeight: 20 }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, tag: { color: c.muted, fontSize: 11, backgroundColor: c.soft, borderRadius: 4, paddingHorizontal: 7, paddingVertical: 3 }, delete: { color: c.danger, fontSize: 12 }, empty: { color: c.muted, textAlign: 'center', borderWidth: 1, borderStyle: 'dashed', borderColor: c.line, borderRadius: 10, padding: 30 }, notice: { borderWidth: 1, borderColor: 'rgba(180,95,88,.28)', backgroundColor: '#fff7f5', borderRadius: 9, padding: 11 }, noticeText: { color: c.danger, fontSize: 12, lineHeight: 18 },
  healthCard: { backgroundColor: c.paper, borderWidth: 1, borderColor: c.line, borderRadius: 12, padding: 18, gap: 12 }, healthHead: { flexDirection: 'row', alignItems: 'center', gap: 9 }, healthIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' }, healthTitle: { color: c.ink, fontSize: 17, fontWeight: '700', flex: 1 }, total: { color: c.green, backgroundColor: c.pale, borderRadius: 5, paddingVertical: 4, paddingHorizontal: 8, fontSize: 12 }, healthRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: c.line }, grow: { flex: 1 }, recordDate: { color: c.ink, fontSize: 13, fontWeight: '700', marginBottom: 4 }, emptyInline: { color: c.muted, fontSize: 13 }, portrait: { width: '100%', aspectRatio: 1, borderRadius: 12, backgroundColor: c.soft }, aboutName: { color: c.ink, fontSize: 30, fontWeight: '700', marginTop: 6 }, nick: { color: c.green, fontSize: 14, fontWeight: '400' }, aboutIntro: { color: c.muted, fontSize: 14, lineHeight: 24 }, profile: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: c.line, marginVertical: 8 }, profileRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13 }, profileKey: { color: c.muted, fontSize: 13 }, profileValue: { color: c.ink, fontSize: 13 }, trait: { color: c.muted, fontSize: 13, backgroundColor: c.paper, borderColor: c.line, borderWidth: 1, borderRadius: 7, paddingVertical: 8, paddingHorizontal: 11 },
  viewer: { flex: 1, backgroundColor: 'rgba(22,31,24,.84)' }, viewerSafe: { flex: 1, justifyContent: 'center', padding: 18 }, close: { alignSelf: 'flex-end', marginBottom: 16, backgroundColor: c.paper, borderRadius: 9, paddingVertical: 9, paddingHorizontal: 13 }, closeText: { color: c.ink, fontSize: 13 }, viewerPanel: { backgroundColor: c.paper, borderRadius: 14, overflow: 'hidden', paddingBottom: 16 }, viewerImage: { width: '100%', aspectRatio: 1, backgroundColor: c.ink }, viewerQuote: { color: c.ink, fontSize: 24, lineHeight: 40, padding: 34, textAlign: 'center' }, viewerTitle: { color: c.ink, fontSize: 20, fontWeight: '700', paddingHorizontal: 16, paddingTop: 15, paddingBottom: 6 }, viewerBody: { paddingHorizontal: 16 },
  keyboardAvoider: { flex: 1 }, sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(25,38,28,.35)' }, sheet: { maxHeight: '88%', backgroundColor: c.paper, borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: 'hidden' }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderColor: c.line, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 12 }, sheetTitle: { color: c.ink, fontSize: 20, fontWeight: '700' }, sheetContent: { padding: 20, gap: 12 }, sheetLead: { color: c.muted, fontSize: 13 }, input: { borderWidth: 1, borderColor: c.line, borderRadius: 9, paddingHorizontal: 12, paddingVertical: 11, backgroundColor: '#f8faf7', color: c.ink, fontSize: 14 }, textarea: { minHeight: 92, textAlignVertical: 'top' }, mediaPicker: { borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(62,109,71,.45)', borderRadius: 9, padding: 14, backgroundColor: '#f3f8f1', gap: 4 }, mediaPickerTitle: { color: c.green, fontSize: 14, fontWeight: '700' }, mediaPickerHint: { color: c.muted, fontSize: 12 }, button: { alignItems: 'center', backgroundColor: c.green, borderRadius: 9, paddingVertical: 14, marginTop: 4 }, disabled: { opacity: .55 }, buttonText: { color: '#fff', fontSize: 15, fontWeight: '700' },
})
